# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160624_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='position',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
